contacts:
  photo:
    storage: etc/photos
    resize-width: 150
    resize-height: 150
    
spring:
  jpa:
    hibernate:
      ddl-auto: validate

flyway:
  enabled: true

security:
  user:
    name: admin
    password: admin123
  basic:
    realm: Please provide your authentication details